spring:
  datasource:
    url: jdbc:mysql://localhost:3306/register
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

